### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by autowp** [zendframework/zend-mvc-console#10]
In situations when no routes matched or exception occurred console output is empty.
I've try to find why and stops on [Zend\Mvc\Console\View\DefaultRenderingStrategy::render()](https://github.com/zendframework/zend-mvc-console/blob/master/src/View/DefaultRenderingStrategy.php#L47)

Banner & usage content not prints too.

How expects that code print response to output? Result from response prints somewhere else?

My current solution is https://github.com/autowp/zend-mvc-console/commit/938db2e470ba867e568b9f0a9d7580b250856c14 but i think i missed something?

**Comment by zzwang** [comment]
I have this problem too. Should I set config of responseSender?

**Comment by weierophinney** [comment]
Please see [my comment on #12](https://github.com/zendframework/zend-mvc-console/issues/12#issuecomment-243198546) for a workaround; I'll have a new version of zend-mvc tagged shortly addressing the issue.

**Comment by weierophinney** [comment]
To get the fix, please update your zend-mvc to 3.0.3:

``` bash
$ composer require "zendframework/zend-mvc:^3.0.3"
```

**Comment by finalxcode** [comment]
@weierophinney  i use zendframework/zend-mvc:^3.0.4, this problem is resolved, thanks
