### ISSUE TITLE
Call to private method Zend\Mvc\Console\View\ViewManager::getView() from context 'ZF\Rpc\Module'

### ISSUE THREAD

**Issue by waltertamboer** [zendframework/zend-mvc-console#14]
When enabling the module in combination with Apigility, the error `Call to private method Zend\Mvc\Console\View\ViewManager::getView() from context 'ZF\Rpc\Module'` is thrown. This is because the `getView` method is private while it is public in `Zend\Mvc\View\Http\ViewManager`.

I guesst the onBootstrap method in ZF\Rpc\Module::onBootstrap should not be executed while in console mode but one does not want to introduce a hard dependency on `Zend\Console`

**Comment by weierophinney** [comment]
Promoted `getView()` to public visibility, and released with 1.1.11.
