### ISSUE TITLE
[Question] ConfigProvider methods

### ISSUE THREAD

**Issue by boesing** [zendframework/zend-mvc-console#19]
Hey there,

I've seen those `ConfigProvider` objects in various zend modules.
Wanted to know where those methods you implemented are documented or if they even need to be documented (if not, why would we implement them as public?)...

There is [Advanced Configuration](https://framework.zend.com/manual/2.4/en/tutorials/config.advanced.html#configuration-mapping-table) documentation, which is presenting some `zendframework/zend-modulemanager` methods which are provided by `Feature\*`-Interfaces. Instead of providing `getControllerPluginConfig` you defined `getPluginConfig`

Could someone give me a shot where the new definition can be found? 
Wondering why there ain't any interfaces at all. I liked the `Feature\*`-Interfaces because I could create a module-manager supporting wrapper for `zendframework/zend-config-aggregator`, which provides the `__invoke` method for a `Module` which implements `ConfigProviderInterface`, e.g.

**Comment by froschdesign** [comment]
@boesing 
Only a side note: the provided link points to the old and outdated documentation. The current documentation can be found here: https://docs.zendframework.com/tutorials/advanced-config/#configuration-mapping-table.

**Comment by weierophinney** [comment]
@boesing The `ConfigProvider` classes are present to allow components to provide configuration for non-zend-mvc applications; the original use case was for Expressive, but these can be used literally anywhere. We added `Module` clases to each component exposing configuration as well to allow easy usage in zend-mvc, as, in some cases, we also needed to do other wiring other than configuration (e.g., registering event listeners during bootstrap).

All `ConfigProvider` classes need to do is:

- be invokable
- return an array of configuration
- segregate dependency configuration from other configuration (to allow discovery of services to wire into a dependency injection container)

In many cases (most?) we define additional methods to allow segregating the various _types_ of configuration exposed (`getDependencies()`, `getPluginConfig()`, `getDefaultConfig()`, etc.) mainly for readability, but also to allow for pulling specific configuration where desired (e.g., in `Module` classes, so as to build a configuration array compatible with zend-mvc). These will vary based on component, as different components will have different needs

We chose not to define an interface in this case as we did not want to impose an additional dependency on applications that define configuration providers; these exist precisely to allow de-coupling from specific frameworks (unlike the `Module` classes, which are specifically for zend-mvc applications). In point of fact, I [blogged about this last week](https://framework.zend.com/blog/2017-04-20-config-aggregator.html), demonstrating how you can use zend-config-aggregator (and optionally zend-component-installer) to create a de-coupled configuration system for your application.
