### ISSUE TITLE
Exceptions thrown inside DelegatorFactory are not rendered in the console

### ISSUE THREAD

**Issue by tylkomat** [zendframework/zend-mvc-console#9]
I'm in the process of migrating my applications and other third party dependencies to ZF3. Inside a `DelegatorFactory`, which delegates the creation process of a `ConsoleController`, a `ServiceNotFoundException` is thrown (due to the new case sensitivity of service names) but it is not rendered into the console.

I was stepping through via debugger and everything looks fine (for my not zend framework internals expert eye), quite close to what happens in my ZF2 Application where the Exception is rendered. 

I can provide more informations if someone tells me where to look.

**Comment by tylkomat** [comment]
The [`$response = $result->getLast()`](https://github.com/zendframework/zend-mvc/blob/af7534c6af35d69442445c7885f04a5b0c453be6/src/Application.php#L335) call holds a `Zend\Mvc\Console\View\ViewModel` but [`$this->response`](https://github.com/zendframework/zend-mvc/blob/af7534c6af35d69442445c7885f04a5b0c453be6/src/Application.php#L346) holds an empty `Zend\Console\Reponse` which is what is rendered in the end: nothing.

Hope that helps.

**Comment by weierophinney** [comment]
I need a bit more information - where is the `$response = $result->getLast()` call happening?

Ideally, if you can provide a minimal reproduce case, that will help us verify the issue and provide a fix.

**Comment by tylkomat** [comment]
The call happens after the Exception is thrown. I put links to the Lines in my previous comment. The call is in Application.php Line 335.

But I think everything is correct there. I was digging more. So the flow continues with completing the request and a `Mvc::EVENT_FINISH` is triggered ([Application.phpL373](https://github.com/zendframework/zend-mvc/blob/af7534c6af35d69442445c7885f04a5b0c453be6/src/Application.php#L373)). In the end the `ConsoleResponseSender` is supposed to render the response. Right? 

The `ConsoleResponseSender::__invoke` method is never called. I was not testing for `ConsoleResponseSender::sendContent`, as my day was over. The `ConsoleResponseSenderDelegatorFactory` was adding the Listener to the Eventmanager though.

**Comment by tylkomat** [comment]
I created a minimal Application since I didn't manage to create a real test case: https://github.com/tylkomat/zf-mvc-console-testcase

Just run `php public/index.php run` after `composer install`.
Running a route that does not exist should also render an error message I suppose, but does not.

**Comment by tylkomat** [comment]
@weierophinney I found the cause of the problem. Here is the flow:
1. SendResponseLIstener is created
2. ConsoleResponseSenderDelegatorFactory delegates creation
3. Delegator calls getEventManager on ConsoleResponseSender
4. new Eventmanager is created and initialized
5. SendResponseEvent is attached
6. because of EventManagerAwareInterface a new Eventmanager is created and added to SendResponseListener which results in the loss of the event attached by the Delegator

**Comment by weierophinney** [comment]
@tylkomat is this resolved with zend-mvc 3.0.3?

**Comment by finalxcode** [comment]
+1

**Comment by tylkomat** [comment]
@weierophinney Sorry for the late response, was working on other Thngs and forgot about it. Yes it's solved.
@finalxcode Thanks for reminding me 🥇

**Comment by finalxcode** [comment]
@tylkomat You are welcome
